/**
 * Reads the text out of a ZIP container, which is what an .xlsx actually is: a ZIP of XML parts.
 *
 * No spreadsheet library. Two reasons it isn't worth one here: the npm `xlsx` package is
 * deprecated in favour of a self-hosted tarball (a supply-chain smell for a single admin dialog),
 * and nothing here needs to understand sheets, rows or cells anyway. Email addresses land in
 * `xl/sharedStrings.xml` as plain `<t>` text, so inflating the XML parts and handing the raw text
 * to extractEmails finds them without modelling the format at all. The same pass therefore works
 * for .docx/.odt/.pptx too, which are also ZIP-of-XML.
 *
 * Decompression is `DecompressionStream("deflate-raw")` - available in every current browser and in
 * Node 18+, so this is testable outside a browser as well as usable inside one.
 *
 * The central directory is the source of truth for entry sizes rather than the local headers:
 * writers that stream their output leave the local header's sizes as zero and put the real values
 * in a trailing data descriptor, so a local-header-only reader silently reads nothing from exactly
 * the files most likely to have been generated by a server.
 */

const EOCD_SIG = 0x06054b50;
const CD_SIG = 0x02014b50;
const MAX_COMMENT = 0xffff;
/** Guards against a hostile or corrupt archive claiming a gigabyte-sized member. */
const MAX_ENTRY_BYTES = 32 * 1024 * 1024;

type Entry = { name: string; method: number; compressedSize: number; localHeaderOffset: number };

/** Every text-bearing part of the archive, concatenated. Binary members (images, fonts) are
 * skipped - they can't contain an address in readable form and inflating them is wasted work. */
export async function extractTextFromZip(buffer: ArrayBuffer): Promise<string> {
  const view = new DataView(buffer);
  const bytes = new Uint8Array(buffer);
  const entries = readCentralDirectory(view, bytes);

  const parts: string[] = [];
  for (const entry of entries) {
    if (!/\.(xml|rels|txt|csv|json)$/i.test(entry.name)) continue;
    if (entry.compressedSize > MAX_ENTRY_BYTES) continue;
    const data = await readEntry(view, bytes, entry);
    if (data) parts.push(new TextDecoder().decode(data));
  }
  return parts.join("\n");
}

function readCentralDirectory(view: DataView, bytes: Uint8Array): Entry[] {
  // Scans back from the end for the End Of Central Directory signature - it sits at a variable
  // offset because an archive may carry a trailing comment of up to 64KB.
  const minEocd = 22;
  const searchFrom = Math.max(0, bytes.length - (MAX_COMMENT + minEocd));
  let eocd = -1;
  for (let i = bytes.length - minEocd; i >= searchFrom; i--) {
    if (view.getUint32(i, true) === EOCD_SIG) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error("not a zip archive");

  const count = view.getUint16(eocd + 10, true);
  let offset = view.getUint32(eocd + 16, true);

  const entries: Entry[] = [];
  for (let i = 0; i < count; i++) {
    if (offset + 46 > bytes.length || view.getUint32(offset, true) !== CD_SIG) break;
    const method = view.getUint16(offset + 10, true);
    const compressedSize = view.getUint32(offset + 20, true);
    const nameLen = view.getUint16(offset + 28, true);
    const extraLen = view.getUint16(offset + 30, true);
    const commentLen = view.getUint16(offset + 32, true);
    const localHeaderOffset = view.getUint32(offset + 42, true);
    const name = new TextDecoder().decode(bytes.subarray(offset + 46, offset + 46 + nameLen));
    entries.push({ name, method, compressedSize, localHeaderOffset });
    offset += 46 + nameLen + extraLen + commentLen;
  }
  return entries;
}

async function readEntry(view: DataView, bytes: Uint8Array, entry: Entry): Promise<Uint8Array | null> {
  const start = entry.localHeaderOffset;
  if (start + 30 > bytes.length) return null;
  // Name/extra lengths come from the LOCAL header here, not the central one: the two are allowed
  // to carry different extra fields, and it's the local one that determines where data begins.
  const nameLen = view.getUint16(start + 26, true);
  const extraLen = view.getUint16(start + 28, true);
  const dataStart = start + 30 + nameLen + extraLen;
  const data = bytes.subarray(dataStart, dataStart + entry.compressedSize);
  if (data.length === 0) return null;

  if (entry.method === 0) return data;
  if (entry.method !== 8) return null; // stored and deflate are all a real .xlsx ever uses

  try {
    const stream = new Blob([data as unknown as BlobPart]).stream().pipeThrough(new DecompressionStream("deflate-raw"));
    return new Uint8Array(await new Response(stream).arrayBuffer());
  } catch {
    return null;
  }
}

export function isZipContainer(file: File): boolean {
  const name = file.name.toLowerCase();
  return name.endsWith(".xlsx") || name.endsWith(".xlsm") || name.endsWith(".docx") || name.endsWith(".odt") || name.endsWith(".ods");
}
